doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '%app.server_version%'
                charset: utf8
                url: '%app.database_url%'
                default_table_options:
                    charset: utf8
                    collate: utf8_general_ci

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Admin:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/packages/doctrine/Admin'
                prefix: 'App\Admin\Entity'
                alias: App\Admin\Entity

            Api\Version:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/packages/doctrine/Api'
                prefix: 'App\Api\Entity\Version'
                alias: App\Api\Entity\Version

            Core:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/packages/doctrine/Core'
                prefix: 'App\Core\Entity'
                alias: App\Core\Entity
            Front:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/packages/doctrine/Front'
                prefix: 'App\Front\Entity'
                alias: App\Front\Entity
